version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    env_file:
      - ./postgres_config.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
